<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-QPFEMJR" failures="0" tests="1" name="Failing test" time="0.029" errors="0" timestamp="2021-03-28T09:50:43 EDT">
  <testcase classname="base.TestBase" name="@BeforeSuite setUP" time="5.591">
    <failure type="java.lang.NumberFormatException" message="null">
      <![CDATA[java.lang.NumberFormatException: null
at java.base/java.lang.Integer.parseInt(Integer.java:614)
at java.base/java.lang.Integer.parseInt(Integer.java:770)
at base.TestBase.setUP(TestBase.java:144)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeSuite setUP -->
  <testcase classname="testCases.TestFailure" name="failure" time="0.0">
    <skipped/>
  </testcase> <!-- failure -->
</testsuite> <!-- Failing test -->
